#!/bin/sh

cpus="`grep ^processor /proc/cpuinfo | wc -l`"

if [ -z "$cpus" ]; then
    echo "Cannot determine the number of CPUs, falling back to 1"
    cpus=1
else
    echo "Number of CPUs: $cpus"
fi

debuild --preserve-envvar=MAKEFLAGS --no-tgz-check -b -uc -us -j$cpus
