.TH QSSEDITOR 1 "MARCH 21, 2014"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
qsseditor \- a tool to to edit and preview Qt style sheets
.SH SYNOPSIS
.B qsseditor
\fB[QSS file to open at startup]\fR
.br
.SH DESCRIPTION
Qt is a cross-platform C++ application framework. Qt's primary feature
is its rich set of widgets that provide standard GUI functionality.

The QSS Editor is a tool to edit and preview Qt style sheets. It provides
a simple interface with autocompletion support.
.SH OPTIONS
The options which apply to the
\fBqsseditor\fR
command are:
.PP
\fB[QSS file to open at startup]\fR
.RS 4
Opens the specified QSS file at startup
.RE
.SH AUTHOR
qsseditor was written by Dmitry Baryshev.
.PP
This manual page was written by Dmitry Baryshev <linuxsquirrel.dev@gmail.com>,
for the Debian project (but may be used by others).
